const FETCH_INIT = 'FETCH_INIT';
const FETCH_MEALS = 'FETCH_MEALS';
const FETCH_FAIL = 'FETCH_FAIL';
const CHANGE_FILTER = 'CHANGE_FILTER';
const FETCH_CATEGORY = 'FETCH_CATEGORY';
const FETCH_MEAL = 'FETCH_MEAL';
const SELECT_MEAL = 'SELECT_MEAL';
const FETCH_INIT_MEAL = 'FETCH_INIT_MEAL';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_MEAL_ERROR = 'FETCH_MEAL_ERROR';
const RESET_STEP = 'RESET_STEP';

export {
  FETCH_INIT,
  FETCH_MEALS,
  FETCH_FAIL,
  CHANGE_FILTER,
  FETCH_CATEGORY,
  FETCH_MEAL,
  SELECT_MEAL,
  FETCH_INIT_MEAL,
  FETCH_SUCCESS,
  FETCH_MEAL_ERROR,
  RESET_STEP,
};
