const FETCH_INIT = 'FETCH_INIT';
const FETCH_MEALS = 'FETCH_MEALS';
const FETCH_FAIL = 'FETCH_FAIL';
const CHANGE_FILTER = 'CHANGE_FILTER';
const FETCH_CATEGORY = 'FETCH_CATEGORY';

export {
  FETCH_INIT,
  FETCH_MEALS,
  FETCH_FAIL,
  CHANGE_FILTER,
  FETCH_CATEGORY,
};
